name: KMP Wasm Workflow

on:
  push:
    branches: [ "main.yaml" ]
    paths:
      - "!**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build wasm application
        run: ./gradlew wasmJsBrowserDistribution

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: composeApp/build/dist/wasmJs/productionExecutable/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy artifact to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
